services:
  tube-explore:
    build: .
    ports:
      - "8000:8000"
    environment:
      CONFIG_DIRECTORY: /app/config
      DOWNLOAD_DIRECTORY: /app/downloads
    volumes:
      - ./downloads:/app/downloads
      - ./config:/app/config
      - ../temp:/temp
    networks:
      - tube-net

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - "7878:7878"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Etc/UTC
    volumes:
      - /home/prakhar/projects/radarr-config:/config
      - ./downloads/radarr:/not/regular/path
    networks:
      - tube-net

networks:
  tube-net:
    driver: bridge
