services:
  tube-explore:
    build: .
    ports:
      - "8000:8000"
    environment:
      CONFIG_DIRECTORY: /app/config
      OUTBOX_DIRECTORY: /app/outbox
    volumes:
      - downloads:/app/downloads
      - config:/app/config
      - outbox:/app/outbox

volumes:
  downloads:
  config:
  outbox:
